package practisepackage;

import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class AnnotationExecution_TestInSameClassOrderOfExecution {

	@BeforeSuite
	public void configurebs()
	{
		System.out.println("connect to databse");
	}
	
	@BeforeClass
	public void configurebc()
	{
		System.out.println("launch the browser");
	}
	
	@BeforeMethod
	public void configbm()
	{
		System.out.println("login to application as a staff");
	}
	
	@Test
	public void openAccount()
	{
		System.out.println("apply for account through open account");
		System.out.println("approve autogenerated application number");
	}
	
	@AfterMethod
	public void confifam()
	{
		System.out.println("logout from the application");
	}
	
	@BeforeMethod
	public void configurebm()
	{
		System.out.println("login into application");
	}
	@Test
	public void approveaccount()
	{
		System.out.println("approve the account");
		System.out.println(" view in active customers of approved account");
	}
	
	@AfterMethod
	public void configuream()
	{
		System.out.println("logout from the application as a staff");
	}
	
	@AfterClass
	public void configureac()
	{
		System.out.println("close the browser");
	}
	
	@AfterSuite
	public void configureas()
	{
		System.out.println("close the connection of databse");
	}
}
